import type { ApplicationDraft, JobApplication } from "./types";

export const emptyDraft: ApplicationDraft = {
  company: "",
  role: "",
  jobUrl: "",
  dateApplied: new Date().toISOString().slice(0, 10),
  status: "Applied",
  notes: "",
  deadline: "",
  resume: "",
  recruiter: "",
  recruiterEmail: "",
  nextAction: "",
};

export const seedApplications: JobApplication[] = [
  {
    id: "stripe-product-designer",
    company: "Stripe",
    role: "Product Designer",
    jobUrl: "https://stripe.com/jobs",
    dateApplied: "2026-05-20",
    status: "Interview",
    resume: "resume_v3.pdf",
    recruiter: "Jamie Lee",
    recruiterEmail: "jamie@stripe.com",
    deadline: "2026-06-15",
    notes: "Second round scheduled for June 10th",
    nextAction: "Prepare portfolio walkthrough",
    lastActionDate: "2026-06-03",
  },
  {
    id: "linear-frontend-engineer",
    company: "Linear",
    role: "Frontend Engineer",
    jobUrl: "https://linear.app/careers",
    dateApplied: "2026-05-28",
    status: "Screening",
    resume: "resume_v4.pdf",
    recruiter: "Morgan Chen",
    recruiterEmail: "morgan@linear.app",
    deadline: "2026-06-20",
    notes: "Take-home assignment pending",
    nextAction: "Submit coding challenge",
    lastActionDate: "2026-05-30",
  },
  {
    id: "notion-ux-researcher",
    company: "Notion",
    role: "UX Researcher",
    jobUrl: "https://www.notion.so/careers",
    dateApplied: "2026-05-10",
    status: "Ghosted",
    resume: "resume_v2.pdf",
    recruiter: "",
    recruiterEmail: "",
    deadline: "",
    notes: "Applied via LinkedIn",
    nextAction: "Send follow-up email",
    lastActionDate: "2026-05-17",
  },
];
